services:
    exporter:
        build:
            context: .
        restart: unless-stopped
        env_file: .env
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        volumes:
            - ./storage:/storage
